### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by Kurren123** [awood/hawkins#12]
Hi 

I'm new to Ruby, I'm running Windows and installed ruby via `choc install ruby`. This is currently my gemfile: 

```
source "https://rubygems.org"

gem 'jekyll'
gem 'hawkins'
```

When I run `bundle install` I get the following error: 

```
Gem::InstallError: The 'http_parser.rb' native gem requires installed build
tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot
continue.
Make sure that `gem install http_parser.rb -v '0.6.0'` succeeds before bundling.
```

**Comment by Kurren123** [comment]
I figured out the issue, chocolatey wasn't installing ruby and the devkit correctly on windows. I followed the instructions here instead: http://jekyll-windows.juthilo.com/1-ruby-and-devkit/

However now I am getting 
```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins/websockets.rb:2:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins.rb:8:in `<module:Hawkins>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/hawkins-2.0.5/lib/hawkins.rb:3:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/lib/jekyll/plugin_manager.rb:49:in `require_from_bundler'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.1/exe/jekyll:9:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:22:in `load'
        from C:/Ruby24-x64/bin/jekyll:22:in `<main>'
```

**Comment by awood** [comment]
That stack trace indicates that the problem is in em-websockets and/or eventmachine rather than in Hawkins.

See the advice at https://stackoverflow.com/questions/14824235/rails-cannot-run-app-unable-to-load-the-eventmachine-c-extension and see if that helps.
